[package]
name = "tpfancontrol"
version = "0.1.0"
authors = ["Arnavion <arnavion@gmail.com>"]
edition = "2021"

[dependencies]
cursive = { version = "0.20", default-features = false, features = ["termion-backend"] }
once_cell = "1"
libc = "0.2"
ordered-float = "3"
serde = "1"
toml = "0.5"
